### PR TITLE
feat(pagination): Added pagination support with infinite scroll

### PR DESCRIPTION
**Pull request by dotansimha**
- [x] Depends on https://github.com/apollostack/GitHunt-API/pull/87

### CODE REVIEW

**Comment by kamilkisiela** [comment]
Welcome to GitHunt @dotansimha  :smiley: 

Could you do rebase?

**Comment by dotansimha** [comment]
@kamilkisiela Done!

**Comment by kamilkisiela** [comment]
Okay, now waiting for the apollostack/GitHunt-API#87

**Comment by dotansimha** [comment]
@kamilkisiela the GitHunt-API PR merged, and I fixed all lint issues :)

**Comment by kamilkisiela** [comment]
Thanks @dotansimha :) :clap:

**Pull request merged**
