### PR TITLE
Rc5

### PR DESCRIPTION
**Pull request by Tallyb**
Upgrade apollo server to 0.2
Upgrade angular to RC5

### CODE REVIEW

**Comment by kamilkisiela** [comment]
@Tallyb Could you sign the Meteor Contributor Agreement so I can merge it?

**Comment by Tallyb** [comment]
@kamilkisiela  did...

**Comment by kamilkisiela** [comment]
Oh, my mistake :+1:

**Comment by kamilkisiela** [comment]
@Tallyb I'll remove `webpack-dashboard` and also I found a bug but it's on `angular2-apollo` side. Sooo I'm going to fix it, then "merging" kicks in!

**Comment by Tallyb** [comment]
@kamilkisiela  sorry about the webpack-dashboard. never worked out and I forgot to remove.

**Pull request merged**
